name: Develop workflow

on:
  push:
    branches: 
      - "feature**"  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  do-something:
    runs-on: ubuntu-latest
    name: Set the tag
    steps:
      - name: rum
        run: echo github.event.head_commit.message
  merge-develop-to-feature:
    if: ${{ contains(github.event.head_commit.message, 'deploy:') }}
    name: Merge develop -> feature
    runs-on: ubuntu-latest
    steps:
      - name: Usar direct merge del marketplace        
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: ${{ github.ref }}
          
  merge-feature-to-develop:
    if: ${{ contains(github.event.head_commit.message, 'deploy:') }} 
    name: Merge feature -> develop
    runs-on: ubuntu-latest
    steps:
      - name: Usar direct merge del marketplace
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch:  ${{ github.ref }}
          target-branch: develop  
  
